package analyzer_test

import (
	"strings"
	"testing"

	"github.com/gopherust-io/goalign/internal/analyzer"
	"github.com/gopherust-io/goalign/internal/layout"
)

func TestFieldIgnore(t *testing.T) {
	src := `package p
type S struct {
	A bool // goalign:ignore
	B int64
	C bool
}
`
	res, err := analyzer.AnalyzeSource("x.go", []byte(src), layout.SizerFor("amd64"))
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Issues) == 0 {
		t.Fatal("expected issue on remaining fields")
	}
	iss := res.Issues[0]
	if len(iss.Suggested) != 0 {
		t.Fatalf("autofix should be skipped with field ignore: %+v", iss.Suggested)
	}
	if len(iss.BoolPack) != 0 {
		t.Fatalf("bool-pack must be cleared with field ignore: %v", iss.BoolPack)
	}
	// Full-struct metrics (A bool + pad + B int64 + C bool + trail) = 24 on amd64.
	if iss.TotalSize != 24 {
		t.Fatalf("total=%d want 24 (full struct, not filtered)", iss.TotalSize)
	}
	found := false
	for _, n := range iss.Notes {
		if strings.HasPrefix(n, "field-ignore") {
			found = true
		}
	}
	if !found {
		t.Fatalf("notes=%v", iss.Notes)
	}
}

func TestMatchGlob(t *testing.T) {
	t.Parallel()
	if !analyzer.MatchGlob("*.pb.go", "api/foo.pb.go") {
		t.Fatal("basename")
	}
	if !analyzer.MatchGlob("**/*.pb.go", "api/v1/foo.pb.go") {
		t.Fatal("**")
	}
	if analyzer.IsGenerated([]byte("// Code generated by protoc. DO NOT EDIT.\npackage p\n")) != true {
		t.Fatal("generated")
	}
}

func TestImportAliasTypeSizes(t *testing.T) {
	src := `package p
import r "io"
type S struct {
	R r.Reader
	A bool
}
`
	sizes := map[string]layout.Info{
		"io.Reader": {Size: 16, Align: 8},
	}
	res, err := analyzer.AnalyzeSourceWithOptions("x.go", []byte(src), analyzer.Options{
		Sizer:     layout.SizerFor("amd64"),
		Policy:    layout.PolicyAtomics,
		TypeSizes: sizes,
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Issues) == 0 {
		t.Fatal("expected issue (r.Reader must resolve via alias)")
	}
	iss := res.Issues[0]
	if iss.TotalSize < 24 {
		t.Fatalf("total=%d; alias unresolved would skip or under-size", iss.TotalSize)
	}
}
